name: PR Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List repository contents
        run: |
          echo "Repository root contents:"
          ls -la

      - name: Prepare build directory
        run: |
          mkdir -p build
          echo "Copying HTML files:"
          cp -v *.html build/ || echo "No HTML files found"
          echo "Copying javascript directory:"
          cp -rv javascript build/ || echo "No javascript directory found"
          echo "Copying images directory:"
          cp -rv images build/ || echo "No images directory found"
          echo "Build directory contents:"
          ls -R build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-preview/${{ github.event.pull_request.number }}
          allow_empty_commit: true
          force_orphan: true

      - name: Comment PR
        uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = 'Noobs-Unblocked-Games-Beta-FINAL';
            const issue_number = context.issue.number;
            const pr_number = context.payload.pull_request.number;
            
            console.log(`Owner: ${owner}, Repo: ${repo}, Issue Number: ${issue_number}, PR Number: ${pr_number}`);
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: `✅ PR preview deployed to https://${owner}.github.io/${repo}/pr-preview/${pr_number}/`
            });
