name: PR Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare build directory
        run: |
          mkdir -p build
          cp -r *.html javascript images build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: pr-preview/${{ github.event.pull_request.number }}
          force_orphan: true

      - name: Comment PR
        uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: context.issue.number,
              body: `✅ PR preview deployed to https://${context.repo.owner}.github.io/${context.repo.name}/pr-preview/${context.payload.pull_request.number}/`
            })
