name: PR Preview Deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare PR preview
        run: |
          mkdir -p pr-preview/${{ github.event.pull_request.number }}
          cp -R * pr-preview/${{ github.event.pull_request.number }}/ || true
          echo "Contents of PR preview directory:"
          ls -R pr-preview/${{ github.event.pull_request.number }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pr-preview/${{ github.event.pull_request.number }}
          destination_dir: pr-preview/${{ github.event.pull_request.number }}
          publish_branch: pr-previews
          force_orphan: false
          keep_files: true

      - name: Comment PR
        uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = 'Noobs-Unblocked-Games-1.1';
            const pr_number = context.payload.pull_request.number;
            
            console.log(`Owner: ${owner}, Repo: ${repo}, PR Number: ${pr_number}`);
            
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: context.issue.number,
              body: `✅ PR preview deployed to https://${owner}.github.io/${repo}/pr-preview/${pr_number}/`
            });

      - name: Check deployment
        run: |
          echo "Checking deployment..."
          curl -sS "https://${{ github.repository_owner }}.github.io/Noobs-Unblocked-Games-1.1/pr-preview/${{ github.event.pull_request.number }}/" || echo "Deployment not accessible yet"
